# Generated by Django 5.1.15 on 2026-09-08 08:21

import django.db.models.deletion
import django.utils.timezone
import rooms.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('host_player_id', models.UUIDField(help_text='UUID of the current room host')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting in Lobby'), ('PLAYING', 'Match In Progress'), ('FINISHED', 'Match Finished'), ('CLOSED', 'Room Closed')], db_index=True, default='WAITING', max_length=20)),
                ('max_players', models.PositiveSmallIntegerField(default=6)),
                ('house_rules', models.JSONField(default=rooms.models.default_house_rules)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_code', 'status'], name='idx_rooms_code_status')],
            },
        ),
        migrations.CreateModel(
            name='RoomPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('nickname', models.CharField(max_length=30)),
                ('seat_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_host', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('connected', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rooms.room')),
            ],
            options={
                'db_table': 'room_players',
                'ordering': ['seat_order', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_turns', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('final_scoreboard', models.JSONField(default=dict)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='rooms.room')),
                ('winner_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='rooms.roomplayer')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-finished_at'],
            },
        ),
        migrations.AddIndex(
            model_name='roomplayer',
            index=models.Index(fields=['room', 'session_token'], name='idx_players_room_session'),
        ),
    ]
